#! /bin/sh
git clone https://github.com/gregcorbett/openblocks.git && \
cd openblocks && \
mvn install && \
cd .. && \
rm -rf openblocks && \
export M2_HOME=/usr/local/maven && \
export PATH=${M2_HOME}/bin:${PATH} && \
echo $M2_HOME && \
echo $PATH && \
mvn -version && \
# Get the working copy of the jar file from github
wget -P ~/.m2/repository/edu/mit/openblocks/1.0.2-SNAPSHOT/ https://github.com/gregcorbett/openblocks/releases/download/v1.0/openblocks-1.0.2-SNAPSHOT.jar
