#! /bin/sh
git clone https://github.com/gregcorbett/openblocks.git && \
cd openblocks && \
mvn install && \
cd .. && \
rm -rf openblocks && \
export M2_HOME=/usr/local/maven && \
export PATH=${M2_HOME}/bin:${PATH} && \
echo $M2_HOME && \
echo $PATH && \
mvn -version
