#! /bin/sh

mvn validate
mvn install
cd ~/.m2/repository/edu/mit/openblocks/1.0.2-SNAPSHOT
mv openblocks-1.0.2-SNAPSHOT.jar.lastUpdated openblocks-1.0.2-SNAPSHOT.jar
mv openblocks-1.0.2-SNAPSHOT.pom.lastUpdated openblocks-1.0.2-SNAPSHOT.pom
rm openblocks-1.0.2-SNAPSHOT.jar
wget https://github.com/gregcorbett/openblocks/releases/download/v1.0/openblocks-1.0.2-SNAPSHOT.jar
cd ~/ardublock
mvn install
cd ..
